// Listas estáticas de classificação fiscal usadas em selects/datalists do frontend.
// Substituem o endpoint /reference-options/classification (que nunca foi implementado no backend).

export const CST_ICMS = [
  { code: '00', description: 'Tributada integralmente' },
  { code: '10', description: 'Tributada e com cobrança de ICMS por ST' },
  { code: '20', description: 'Com redução de base de cálculo' },
  { code: '30', description: 'Isenta/não tributada e com cobrança de ICMS por ST' },
  { code: '40', description: 'Isenta' },
  { code: '41', description: 'Não tributada' },
  { code: '50', description: 'Suspensão' },
  { code: '51', description: 'Diferimento' },
  { code: '60', description: 'ICMS cobrado anteriormente por ST' },
  { code: '61', description: 'Tributação monofásica sobre combustíveis cobrada anteriormente' },
  { code: '70', description: 'Com redução de BC e cobrança de ICMS por ST' },
  { code: '90', description: 'Outros' },
]

export const CSOSN = [
  { code: '101', description: 'Tributada com permissão de crédito' },
  { code: '102', description: 'Tributada sem permissão de crédito' },
  { code: '103', description: 'Isenção de ICMS para faixa de receita bruta' },
  { code: '201', description: 'Tributada com permissão de crédito e com cobrança de ICMS por ST' },
  { code: '202', description: 'Tributada sem permissão de crédito e com cobrança de ICMS por ST' },
  { code: '203', description: 'Isenção de ICMS para faixa de receita bruta e com cobrança de ICMS por ST' },
  { code: '300', description: 'Imune' },
  { code: '400', description: 'Não tributada pelo Simples Nacional' },
  { code: '500', description: 'ICMS cobrado anteriormente por substituição tributária ou por antecipação' },
  { code: '900', description: 'Outros' },
]

// SPED registro 0200 — tipo do item.
export const TIPO_ITEM = [
  { code: '00', description: 'Mercadoria para revenda' },
  { code: '01', description: 'Matéria-prima' },
  { code: '02', description: 'Embalagem' },
  { code: '03', description: 'Produto em processo' },
  { code: '04', description: 'Produto acabado' },
  { code: '05', description: 'Subproduto' },
  { code: '06', description: 'Produto intermediário' },
  { code: '07', description: 'Material de uso e consumo' },
  { code: '08', description: 'Ativo imobilizado' },
  { code: '09', description: 'Serviços' },
  { code: '10', description: 'Outros insumos' },
  { code: '99', description: 'Outras' },
]

// CST PIS/COFINS — comuns em entradas e saídas.
export const CST_PIS_COFINS = [
  { code: '01', description: 'Operação tributável (BC=receita bruta)' },
  { code: '02', description: 'Operação tributável (BC=receita - exclusões)' },
  { code: '03', description: 'Operação tributável (BC=qtde vendida)' },
  { code: '04', description: 'Operação tributável (monofásica - revenda)' },
  { code: '05', description: 'Operação tributável (ST)' },
  { code: '06', description: 'Operação tributável (alíquota zero)' },
  { code: '07', description: 'Operação isenta' },
  { code: '08', description: 'Operação sem incidência' },
  { code: '09', description: 'Operação com suspensão' },
  { code: '49', description: 'Outras operações de saída' },
  { code: '50', description: 'Crédito (aquisição tributada)' },
  { code: '51', description: 'Crédito (aquisição tributável - BC exclusões)' },
  { code: '52', description: 'Crédito (aquisição tributável - BC qtde)' },
  { code: '53', description: 'Crédito (aquisição tributável de ent. não cumulat.)' },
  { code: '54', description: 'Crédito (aquisição ST)' },
  { code: '55', description: 'Crédito (aquisição tributável - alíquota zero)' },
  { code: '56', description: 'Crédito (aquisição isenta)' },
  { code: '60', description: 'Crédito (aquisição – importação)' },
  { code: '66', description: 'Crédito presumido (aquisição vinculada)' },
  { code: '67', description: 'Crédito presumido (outras operações)' },
  { code: '70', description: 'Operação sem crédito/débito' },
  { code: '71', description: 'Operação de aquisição sem crédito (suspensão)' },
  { code: '72', description: 'Operação de aquisição sem crédito (alíquota zero)' },
  { code: '73', description: 'Operação de aquisição sem crédito (sem incidência)' },
  { code: '74', description: 'Operação de aquisição sem crédito (monofásica)' },
  { code: '75', description: 'Operação de aquisição sem crédito (ST)' },
  { code: '98', description: 'Outras operações de entrada' },
  { code: '99', description: 'Outras operações' },
]

// CFOPs de entrada (1xxx, 2xxx, 3xxx) — destinatário recebendo NF-e.
export const CFOP_ENTRADA = [
  { code: '1101', description: 'Compra p/ industrialização' },
  { code: '1102', description: 'Compra p/ comercialização' },
  { code: '1111', description: 'Compra p/ industrialização (futura)' },
  { code: '1116', description: 'Compra p/ industrialização (OP mercantil)' },
  { code: '1117', description: 'Compra p/ comercialização (OP mercantil)' },
  { code: '1120', description: 'Compra p/ industrialização (Zona Franca)' },
  { code: '1121', description: 'Compra p/ comercialização (Zona Franca)' },
  { code: '1122', description: 'Compra p/ industrialização (ALC)' },
  { code: '1124', description: 'Industrialização (encomenda)' },
  { code: '1125', description: 'Industrialização (outra empresa)' },
  { code: '1126', description: 'Compra p/ uso/consumo (Zona Franca)' },
  { code: '1128', description: 'Compra p/ ativo (Zona Franca)' },
  { code: '1151', description: 'Transferência p/ industrialização' },
  { code: '1152', description: 'Transferência p/ comercialização' },
  { code: '1153', description: 'Transferência de energia elétrica' },
  { code: '1154', description: 'Transferência p/ uso/consumo' },
  { code: '1159', description: 'Entrada decorrente do fornec. prod. ou prest. serv.' },
  { code: '1201', description: 'Devolução de venda (industrialização)' },
  { code: '1202', description: 'Devolução de venda (comercialização)' },
  { code: '1203', description: 'Devolução de venda (ativo)' },
  { code: '1204', description: 'Devolução de venda (uso/consumo)' },
  { code: '1251', description: 'Compra de energia elétrica' },
  { code: '1252', description: 'Compra de energia elétrica (comercialização)' },
  { code: '1253', description: 'Compra de energia elétrica (processo industrial)' },
  { code: '1254', description: 'Compra de energia elétrica (uso/consumo)' },
  { code: '1301', description: 'Prestação de serviço de comunicação' },
  { code: '1302', description: 'Prestação de serviço de comunicação (SN)' },
  { code: '1351', description: 'Prestação de serviço de transporte (SP)' },
  { code: '1352', description: 'Prestação de serviço de transporte (SN)' },
  { code: '1401', description: 'Compra p/ industrialização (ST)' },
  { code: '1403', description: 'Compra p/ comercialização (ST)' },
  { code: '1406', description: 'Compra p/ ativo (ST)' },
  { code: '1407', description: 'Compra p/ uso/consumo (ST)' },
  { code: '1408', description: 'Transferência p/ industrialização (ST)' },
  { code: '1409', description: 'Transferência p/ comercialização (ST)' },
  { code: '1410', description: 'Devolução de venda (ST)' },
  { code: '1411', description: 'Devolução de venda p/ comercializ. (ST)' },
  { code: '1414', description: 'Retorno de prod. industrializada (ST)' },
  { code: '1501', description: 'Entrada (SUFRAMA)' },
  { code: '1551', description: 'Compra p/ ativo imobilizado' },
  { code: '1556', description: 'Compra p/ uso/consumo' },
  { code: '1901', description: 'Entrada para industrialização por encomenda' },
  { code: '1902', description: 'Retorno de mercadoria remetida' },
  { code: '1903', description: 'Entrada p/ consignação mercantil' },
  { code: '1904', description: 'Retorno de remessa p/ venda fora' },
  { code: '1905', description: 'Entrada de mercadoria (depósito fechado)' },
  { code: '1906', description: 'Retorno de mercadoria (armazém geral)' },
  { code: '1907', description: 'Retorno de conserto/reparo' },
  { code: '1908', description: 'Entrada de bem (comodato)' },
  { code: '1909', description: 'Retorno de bem (comodato)' },
  { code: '1910', description: 'Entrada de bonificação/doação/brinde' },
  { code: '1911', description: 'Entrada de amostra grátis' },
  { code: '1912', description: 'Entrada de mercadoria (demonstração)' },
  { code: '1913', description: 'Retorno de mercadoria (demonstração)' },
  { code: '1914', description: 'Retorno de mercadoria (exposição/feira)' },
  { code: '1916', description: 'Retorno de mercadoria (conserto/reparo)' },
  { code: '1917', description: 'Entrada de mercadoria em consignação' },
  { code: '1918', description: 'Devolução de mercadoria em consignação' },
  { code: '1919', description: 'Devolução simbólica (consignação)' },
  { code: '1920', description: 'Entrada de vasilhame ou sacaria' },
  { code: '1921', description: 'Entrada de vasilhame ou sacaria' },
  { code: '1922', description: 'Lançamento a título de simples faturamento' },
  { code: '1923', description: 'Entrada de mercadoria (armazém geral)' },
  { code: '1924', description: 'Entrada p/ industrialização por conta e ordem' },
  { code: '1925', description: 'Retorno p/ industrialização por conta e ordem' },
  { code: '1926', description: 'Lançamento a título de reclassificação de mercadoria' },
  { code: '1933', description: 'Aquisição de serviço tributado ICMS' },
  { code: '1949', description: 'Outra entrada não especificada' },
  { code: '2101', description: 'Compra p/ industrialização (interestadual)' },
  { code: '2102', description: 'Compra p/ comercialização (interestadual)' },
  { code: '2111', description: 'Compra p/ industrialização (futura, inter.)' },
  { code: '2116', description: 'Compra p/ industrialização (OP mercantil, inter.)' },
  { code: '2117', description: 'Compra p/ comercialização (OP mercantil, inter.)' },
  { code: '2120', description: 'Compra p/ industrialização (Zona Franca, inter.)' },
  { code: '2121', description: 'Compra p/ comercialização (Zona Franca, inter.)' },
  { code: '2122', description: 'Compra p/ industrialização (ALC, inter.)' },
  { code: '2124', description: 'Industrialização efetuada por outra empresa' },
  { code: '2125', description: 'Industrialização efetuada por outra empresa' },
  { code: '2126', description: 'Compra p/ uso/consumo (Zona Franca, inter.)' },
  { code: '2128', description: 'Compra p/ ativo (Zona Franca, inter.)' },
  { code: '2151', description: 'Transferência p/ industrialização (interestadual)' },
  { code: '2152', description: 'Transferência p/ comercialização (interestadual)' },
  { code: '2153', description: 'Transferência de energia elétrica (inter.)' },
  { code: '2154', description: 'Transferência p/ uso/consumo (interestadual)' },
  { code: '2201', description: 'Devolução de venda industrializ. (inter.)' },
  { code: '2202', description: 'Devolução de venda comercializ. (inter.)' },
  { code: '2203', description: 'Devolução de venda ativo (inter.)' },
  { code: '2204', description: 'Devolução de venda uso/consumo (inter.)' },
  { code: '2401', description: 'Compra p/ industrialização (ST, inter.)' },
  { code: '2403', description: 'Compra p/ comercialização (ST, inter.)' },
  { code: '2406', description: 'Compra p/ ativo (ST, inter.)' },
  { code: '2407', description: 'Compra p/ uso/consumo (ST, inter.)' },
  { code: '2408', description: 'Transferência p/ industrialização (ST, inter.)' },
  { code: '2409', description: 'Transferência p/ comercialização (ST, inter.)' },
  { code: '2410', description: 'Devolução de venda (ST, inter.)' },
  { code: '2411', description: 'Devolução de venda p/ comercializ. (ST, inter.)' },
  { code: '2414', description: 'Retorno de prod. industrializada (ST, inter.)' },
  { code: '2501', description: 'Entrada (SUFRAMA, interestadual)' },
  { code: '2551', description: 'Compra p/ ativo imobilizado (interestadual)' },
  { code: '2556', description: 'Compra p/ uso/consumo (interestadual)' },
  { code: '2901', description: 'Entrada p/ industrialização (inter.)' },
  { code: '2902', description: 'Retorno de mercadoria remetida (inter.)' },
  { code: '2903', description: 'Entrada p/ consignação mercantil (inter.)' },
  { code: '2904', description: 'Retorno de remessa p/ venda fora (inter.)' },
  { code: '2910', description: 'Entrada de bonificação/doação (inter.)' },
  { code: '2911', description: 'Entrada de amostra grátis (inter.)' },
  { code: '2912', description: 'Entrada de mercadoria (demonstração, inter.)' },
  { code: '2913', description: 'Retorno de mercadoria (demonstração, inter.)' },
  { code: '2914', description: 'Retorno de mercadoria (exposição, inter.)' },
  { code: '2916', description: 'Retorno de mercadoria (conserto, inter.)' },
  { code: '2917', description: 'Entrada de mercadoria em consignação (inter.)' },
  { code: '2918', description: 'Devolução de mercadoria em consignação (inter.)' },
  { code: '2919', description: 'Devolução simbólica (consignação, inter.)' },
  { code: '2920', description: 'Entrada de vasilhame ou sacaria (inter.)' },
  { code: '2921', description: 'Entrada de vasilhame ou sacaria (inter.)' },
  { code: '2933', description: 'Aquisição de serviço tributado ICMS (inter.)' },
  { code: '2949', description: 'Outra entrada não especificada (inter.)' },
  { code: '3101', description: 'Compra p/ industrialização (importação)' },
  { code: '3102', description: 'Compra p/ comercialização (importação)' },
  { code: '3127', description: 'Compra p/ uso/consumo (importação)' },
  { code: '3201', description: 'Devolução de venda (exportação)' },
  { code: '3551', description: 'Compra p/ ativo imobilizado (importação)' },
]
