sonar.organization=bhubai
sonar.projectKey=BHubAI_bhub-design-system
sonar.projectName=bhub-design-system

sonar.sources=components,src
sonar.exclusions=**/*.stories.tsx,**/*.stories.ts,**/*.test.tsx,**/*.test.ts,**/node_modules/**,**/dist/**,app/**

sonar.tests=components,src
sonar.test.inclusions=**/*.stories.tsx,**/*.stories.ts,**/*.test.tsx,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
